version: "3.8"

services:
  web:
    container_name: my-backend
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./back/:/app
    depends_on:
      - db
    networks:
      - my-network
      - hadoop-hive-spark-docker_sparknet

  adminer:
    container_name: my-adminer
    image: adminer
    ports:
      - 8089:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - my-network
      - hadoop-hive-spark-docker_sparknet

  db:
    container_name: my-db
    image: postgres:14
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - my-network
      - hadoop-hive-spark-docker_sparknet

volumes:
  postgres_data:

networks:
  my-network:
  hadoop-hive-spark-docker_sparknet:
    external: true